config/routes.rb
  Rails.application.routes.draw do
    resources :donor_physical_exams
    resources :donor_screenings
    resources :centres
    resources :donors

    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: "/letter_opener"
    end

    namespace :admin do
       resources :donors
       get "/dashboard", to: "admin#dashboard"
    end

    resources :messages
      resources :operators do
       member do
          get "centre_and_donor_details"
       end
    end
    resources :donor_handbooks
    devise_for :users, controllers: {
    registrations: "users/registrations"
  }
    root "pages#home"
    get "all_questions", to: "questions#all_questions"
    get "home", to: "pages#home"
    get "about", to: "pages#about"
    get "contact", to: "pages#contact"
    get "terms_and_conditions", to: "donors#terms_and_conditions"
    resources :pages, only: [ :edit, :update, :show ]
    resources :donor_history_questionnaires, only: [ :index, :edit, :update, :new, :create ]
    resources :questions do
    collection do
      get :all_donors
    end
  end
  end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here.
    if user.present?
      if user.admin?
        # Admin can manage everything
        can :manage, :all
      elsif user.operator?
        # Define abilities for operators
        can :read, Centre
        can :read, Donor
        can :create, DonorScreening
        can :update, DonorScreening
        can :create, DonorPhysicalExam
        can :update, DonorPhysicalExam

        # Allow specific actions like accessing donor details
        can :view_donor_details, Donor
      else
        # Default abilities for a logged-in user (e.g., donors or others)
        can :read, Question
      end
    else
      # Abilities for guests (not logged in)
      can :read, Question
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/centre.rb
class Centre < ApplicationRecord
    has_many :donor_physical_exams, dependent: :destroy
    has_many :donor_screenings, dependent: :destroy
    has_many :donors, dependent: :destroy
end

app/models/donor.rb
class Donor < ApplicationRecord
  belongs_to :user
  belongs_to :centre
  has_one :donor_physical_exam, dependent: :destroy
  has_one :donor_handbook, dependent: :destroy
  has_one_attached :profile_image
  has_one :donor_screening, dependent: :destroy
  has_many :donor_history_questionnaires, dependent: :destroy
  # validates :first_name, presence: true, length: { maximum: 50 }
  # validates :middle_name, length: { maximum: 50 }, allow_nil: true
  # validates :last_name, presence: true, length: { maximum: 50 }
  # validates :birth_date, presence: true
  # validates :gender, inclusion: { in: ['Male', 'Female', 'Other'], message: "%{value} is not a valid gender" }, allow_nil: true
  # validates :zipcode, presence: true
  # validates :phone_number, presence: true, format: { with: /\A\+?\d{1,4}?[ -]?\(?\d{1,4}?\)?[ -]?\d{1,4}?[ -]?\d{1,4}\z/, message: "must be a valid phone number" }
  # validates :alternate_phone_number, format: { with: /\A\+?\d{1,4}?[ -]?\(?\d{1,4}?\)?[ -]?\d{1,4}?[ -]?\d{1,4}\z/, message: "must be a valid phone number" }, allow_nil: true
  # validates :city, presence: true, length: { maximum: 100 }
  # validates :state, presence: true, length: { maximum: 100 }
  # validates :country, presence: true, length: { maximum: 100 }
  # validates :language, inclusion: { in: ['English', 'Spanish', 'French', 'Other'], message: "%{value} is not a valid language" }, allow_nil: true
  # validates :address_line1, presence: true, length: { maximum: 200 }
  # validates :address_line2, length: { maximum: 200 }, allow_nil: true
  # validates :document, length: { maximum: 1000 }, allow_nil: true
  # validates :arrival_datetime, presence: true
  # validates :potential_fraud, inclusion: { in: ['Yes', 'No'], message: "%{value} is not a valid option" }, allow_nil: true
  def name
    [first_name, middle_name, last_name].reject(&:blank?).join(' ')
  end
end

app/models/donor_handbook.rb
class DonorHandbook < ApplicationRecord
  validates :terms_accepted, acceptance: { accept: true, message: "must be accepted to create a donor handbook" }
  belongs_to :donor
end

app/models/donor_physical_exam.rb
class DonorPhysicalExam < ApplicationRecord
  belongs_to :donor
  belongs_to :centre
  belongs_to :donor_screening
  belongs_to :operator
end

app/models/donor_screening.rb
class DonorScreening < ApplicationRecord
  belongs_to :centre
  belongs_to :donor
  belongs_to :operator
  has_one :donor_physical_exam
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/operator.rb
class Operator < ApplicationRecord
    belongs_to :user
    has_many :donor_screenings
    has_many :donor_physical_exams
    
end

app/models/question.rb
class Question < ApplicationRecord
  validates :text, presence: true
    validates :answer_type, inclusion: { in: [ "true_false", "text" ] }
   has_many :donor_history_questionnaires, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_one :donor, dependent: :destroy
  has_one :operator, dependent: :destroy
   # validates :first_name, :last_name, :email, presence: true
   # validates :aadhar_number, presence: true, length: { is: 12 }, numericality: { only_integer: true }
   enum :role, { donor: 0, admin: 1, operator: 2 }

  def admin?
    self.role == "admin"
  end

 after_create :create_operator_if_needed

private

def create_operator_if_needed
  create_operator if role == 'operator' && operator.nil?
end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centres_helper.rb
module CentresHelper
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/admin/dashboard.html.erb
<div class="con-dashboard">  
  <h1 class="dashboard-title-dashboard">Admin Dashboard</h1>

  <p class="dashboard-welcome-dashboard">
    Welcome, <%= "#{current_user.first_name} #{current_user.last_name}" %>! Manage the application below:
  </p>


  <div class="dashboard-container-dashboard">
    <div class="dashboard-row-dashboard">
      <!-- View All Donors -->
      <div class="dashboard-item-dashboard">
        <div class="dashboard-card-dashboard">
          <div class="dashboard-card-icon-dashboard">
            <i class="fas fa-users"></i>
          </div>
          <div class="dashboard-card-body-dashboard">
            <h3>View All Donors</h3>
            <%= link_to 'Go to Donors', donors_path, class: 'dashboard-btn-dashboard dashboard-btn-info-dashboard' %>
          </div>
        </div>
      </div>

      <!-- View All Messages -->
      <div class="dashboard-item-dashboard">
        <div class="dashboard-card-dashboard">
          <div class="dashboard-card-icon-dashboard">
            <i class="fas fa-users"></i>
          </div>
          <div class="dashboard-card-body-dashboard">
            <h3>View All Messages</h3>
            <%= link_to 'Go to Messages', messages_path, class: 'dashboard-btn-dashboard dashboard-btn-info-dashboard' %>
          </div>
        </div>
      </div>

      <!-- View Questions -->
      <div class="dashboard-item-dashboard">
        <div class="dashboard-card-dashboard">
          <div class="dashboard-card-icon-dashboard">
            <i class="fas fa-question-circle"></i>
          </div>
          <div class="dashboard-card-body-dashboard">
            <h3>View Questions</h3>
            <%= link_to 'Go to Questions', admin_dashboard_path(section: 'questions'), class: 'dashboard-btn-dashboard dashboard-btn-secondary-dashboard' %>
          </div>
        </div>
      </div>

      <!-- View All Centres -->
      <div class="dashboard-item-dashboard">
        <div class="dashboard-card-dashboard">
          <div class="dashboard-card-icon-dashboard">
            <i class="fas fa-hospital"></i>
          </div>
          <div class="dashboard-card-body-dashboard">
            <h3>View All Centres</h3>
            <%= link_to 'Go to Centres', centres_path, class: 'dashboard-btn-dashboard dashboard-btn-info-dashboard' %>
          </div>
        </div>
      </div>

      <!-- View Donor Screenings -->
      <div class="dashboard-item-dashboard">
        <div class="dashboard-card-dashboard">
          <div class="dashboard-card-icon-dashboard">
            <i class="fas fa-clipboard-check"></i>
          </div>
          <div class="dashboard-card-body-dashboard">
            <h3>View Donor Screenings</h3>
            <%= link_to 'Go to Screenings', admin_dashboard_path(section: 'donor_screenings'), class: 'dashboard-btn-dashboard dashboard-btn-warning-dashboard' %>
          </div>
        </div>
      </div>

      

      <!-- View Donor Physical Exams -->
      <div class="dashboard-item-dashboard">
        <div class="dashboard-card-dashboard">
          <div class="dashboard-card-icon-dashboard">
            <i class="fas fa-stethoscope"></i>
          </div>
          <div class="dashboard-card-body-dashboard">
            <h3>View Donor Exams</h3>
            <%= link_to 'Go to Exams', admin_dashboard_path(section: 'donor_physical_exams'), class: 'dashboard-btn-dashboard dashboard-btn-warning-dashboard' %>
          </div>
        </div>
      </div>
      
    </div>
  </div>
</div>

<style>
*{
  overflow: hidden;
}

  /* General Styles */
  .con-dashboard {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 20px;
    margin-top: 10px;
    background-color: var(--primary-bg);
  }

  /* Title Styles */
  .dashboard-title-dashboard {
    text-align: center;
    font-size: 36px;
    font-weight: bold;
    color: white;
    margin-top: 30px;
  }

  /* Welcome Text Styles */
  .dashboard-welcome-dashboard {
    text-align: center;
    font-size: 18px;
    color: white;
  }

  /* Container for the Dashboard Items */
  .dashboard-container-dashboard {
    width: 100%;
    max-width: 1200px;
    padding: 0 15px;
  }

  /* Row for Dashboard Items */
  .dashboard-row-dashboard {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 30px;
  }

  /* Individual Item Card */
  .dashboard-item-dashboard {
    flex: 1;
    min-width: 250px;
    max-width: 350px;
    margin-bottom: 30px;
  }

  /* Card Styles */
  .dashboard-card-dashboard {
    background-color: #fff;
    border-radius: 12px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
    overflow: hidden;
    transition: transform 0.3s ease, box-shadow 0.3s ease;
  }

  .dashboard-card-dashboard:hover {
    transform: translateY(-10px);
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.2);
  }

  .dashboard-card-icon-dashboard {
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: #103460;
    color: white;
    font-size: 40px;
    padding: 20px;
  }

  .dashboard-card-body-dashboard {
    padding: 20px;
    text-align: center;
  }

  .dashboard-card-body-dashboard h3 {
    font-size: 20px;
    font-weight: bold;
    color: #103460;
    margin-bottom: 15px;
  }

  /* Button Styles */
  .dashboard-btn-dashboard {
    padding: 10px 20px;
    font-size: 16px;
    text-decoration: none;
    border-radius: 8px;
    color: white;
    display: inline-block;
    font-weight: bold;
    transition: background-color 0.3s ease;
  }

  .dashboard-btn-info-dashboard {
    background-color: #17a2b8;
  }

  .dashboard-btn-info-dashboard:hover {
    background-color: #138496;
  }

  .dashboard-btn-secondary-dashboard {
    background-color: #18A1B6;
  }

  .dashboard-btn-secondary-dashboard:hover {
    background-color: #138496;
  }

  .dashboard-btn-warning-dashboard {
    background-color: #18A1B6;
  }

  .dashboard-btn-warning-dashboard:hover {
    background-color: #138496;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title><%= content_for(:title) || "Capivis App" %></title>

    <%= yield :head %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <!-- App Icons and Manifest -->
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Render Navbar -->
    <%= render 'layouts/nav/nav' %>
    
    <!-- Main Content -->
    <div class="container mt-5">
       <!-- Notices and Alerts -->
    <% if notice || alert %>
      <div class="container mt-4">
        <%# <p class="alert alert-info notice"><%= notice %></p>
        <%# <p class="alert alert-danger"><%= alert %></p> 
      </div>
    <% end %>
      <%= yield %>
    </div>
   
  </body>
</html>

app/views/layouts/nav/_nav.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= content_for(:title) || "Capivis App" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= javascript_importmap_tags %>
  </head>

  <body>

    <div class="navbar-new">
      <div class="navbar-container-new">
        <%= link_to "Capivis App", root_path, class: "navbar-brand-new" %>

        <div class="navbar-links-new" id="navbarNav">
          <ul class="navbar-nav-new">
            <li class="nav-item-new pad">
              <%= link_to "Home", home_path, class: "nav-link-new" %>
            </li>
            <li class="nav-item-new pad">
              <%= link_to "About", about_path, class: "nav-link-new" %>
            </li>
            <li class="nav-item-new pad">
              <%= link_to "Contact Us", contact_path, class: "nav-link-new" %>
            </li>

            <% if current_user %>
              <% if current_user.role == 'admin' %>
                <li class="nav-item-new">
                  <%= link_to "Admin Dashboard", admin_dashboard_path, class: 'nav-link active-new' %>
                </li>
              <% elsif current_user.role == 'operator' %>
                <li class="nav-item-new">
                  <%= link_to "Operator Dashboard", operators_path, class: 'nav-link active-new' %>
                </li>
              <% end %>
            <% end %>

            <% if user_signed_in? %>
              <li class="nav-item-new">
                <%= link_to "Hi, #{current_user.email}", edit_user_registration_path, class: "nav-link active-new" %>
              </li>
              <li class="nav-item-new">
                <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "nav-link active-new" %>
              </li>
            <% else %>
              <li class="nav-item-new">
                <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary-new" %>
              </li>
              <li class="nav-item ms-2-new">
                <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-secondary-new" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

  </body>
</html>

<style>
  /* Root Colors */
  :root {
    --background: #1a1a2e;
    --color: #ffffff;
    --primary-color: #0f3460;
  }

  * {
    box-sizing: border-box;
    margin: 0;
  }

  body {
    font-family: "Poppins", sans-serif;
    background-color: var(--background);
    color: var(--color);
    letter-spacing: 1px;
    transition: background 0.2s ease;
  }

  a {
    text-decoration: none;
    color: var(--color);
  }

  /* Navbar Styles */
  .navbar-new {
    background-color: var(--primary-color);
    padding: 10px;
    position: fixed;
    width: 100%;
    height: 70px;
    top: 0;
    left: 0;
    z-index: 1000;
  }

  .navbar-container-new {
    display: flex;
    justify-content: space-between;
    align-items: center;
    max-width: 1200px;
    margin: 0 auto;
<%#     margin-top: 10px; %>
  }

  .navbar-brand-new {
    font-size: 1.8rem;
    color: #fff;
    font-weight: bold;
  }

  .navbar-toggler-new {
    font-size: 1.5rem;
    background-color: transparent;
    border: none;
    color: #fff;
    cursor: pointer;
  }

  .navbar-links-new {
    display: flex;
    gap: 20px;
  }

  .navbar-nav-new {
    list-style: none;
    display: flex;
    gap: 20px;
    flex-direction: row;
    margin-top: 7px;
  }

  .nav-item-new {
    
  }

  .nav-link-new {
    color: #fff;
    padding: 8px 15px;
    text-transform: uppercase;
    font-size: 0.95rem;
    border-radius: 5px;
    transition: background-color 0.3s;
  

  }
  .pad{
      padding-top: 6px;
  }

  .nav-link-new:hover {
    background-color: rgba(255, 255, 255, 0.2);
  }

  .nav-link.active-new {
    background-color: var(--primary-color);
  }

  /* Button Styles */
  .btn-new {
    padding: 8px 15px;
    text-transform: uppercase;
    border-radius: 5px;
    transition: background-color 0.3s;
  }

  .btn-primary-new {
    background-color: #007bff;
    color: #fff;
  }

  .btn-secondary-new {
    background-color: #6c757d;
    color: #fff;
  }

  .btn-new:hover {
    background-color: rgba(255, 255, 255, 0.2);
  }

  /* Mobile View */
  @media (max-width: 768px) {
    .navbar-links-new {
      display: none;
      width: 100%;
      background-color: var(--primary-color);
      position: absolute;
      top: 60px;
      left: 0;
      z-index: 1000;
      padding: 10px;
    }

    .navbar-toggler-new {
      display: block;
    }

    .navbar-links-new.active {
      display: flex;
      flex-direction: column;
      align-items: center;
    }
  }
</style>

<script>
  function toggleNavbar() {
    const navbarLinks = document.getElementById('navbarNav');
    navbarLinks.classList.toggle('active');
  }
</script>